<?php

// This file is generated by Composer
require_once 'vendor/autoload.php';

$client = new \Github\Client();
$repositories = $client->api('organization')->repositories('symfony');
var_dump($repositories);


